<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260402120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute la sensibilité des items et les permissions fines par item.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE vault_item ADD is_sensitive BOOLEAN DEFAULT FALSE NOT NULL');
        $this->addSql('CREATE TABLE item_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_id INT NOT NULL, user_id INT NOT NULL, can_view BOOLEAN DEFAULT TRUE NOT NULL, can_edit BOOLEAN DEFAULT FALSE NOT NULL, can_manage_attachments BOOLEAN DEFAULT FALSE NOT NULL, can_reveal_secret BOOLEAN DEFAULT TRUE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_item_permission_item_user ON item_permission (item_id, user_id)');
        $this->addSql('CREATE INDEX idx_item_permission_item_id ON item_permission (item_id)');
        $this->addSql('CREATE INDEX idx_item_permission_user_id ON item_permission (user_id)');
        $this->addSql('ALTER TABLE item_permission ADD CONSTRAINT FK_A80EF5E8126F525E FOREIGN KEY (item_id) REFERENCES vault_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_permission ADD CONSTRAINT FK_A80EF5E8A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE item_permission');
        $this->addSql('ALTER TABLE vault_item DROP is_sensitive');
    }
}
