<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260331100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Creates vault and vault_member tables for sprint 2.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE vault (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, name VARCHAR(160) NOT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_vault_owner_id ON vault (owner_id)');
        $this->addSql('CREATE INDEX idx_vault_created_at ON vault (created_at)');
        $this->addSql('ALTER TABLE vault ADD CONSTRAINT FK_BB9E69857E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE vault_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vault_id INT NOT NULL, user_id INT NOT NULL, role VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_vault_member_vault_user ON vault_member (vault_id, user_id)');
        $this->addSql('CREATE INDEX idx_vault_member_vault_id ON vault_member (vault_id)');
        $this->addSql('CREATE INDEX idx_vault_member_user_id ON vault_member (user_id)');
        $this->addSql('ALTER TABLE vault_member ADD CONSTRAINT FK_B2D3B31C62A82FA FOREIGN KEY (vault_id) REFERENCES vault (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vault_member ADD CONSTRAINT FK_B2D3B31CA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE vault_member');
        $this->addSql('DROP TABLE vault');
    }
}
