<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260331130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les tables du module items.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE vault_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vault_id INT NOT NULL, name VARCHAR(160) NOT NULL, type VARCHAR(255) NOT NULL, username VARCHAR(255) DEFAULT NULL, secret TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_vault_item_vault_id ON vault_item (vault_id)');
        $this->addSql('CREATE INDEX idx_vault_item_created_at ON vault_item (created_at)');
        $this->addSql('ALTER TABLE vault_item ADD CONSTRAINT FK_65A65AE54D11F0A4 FOREIGN KEY (vault_id) REFERENCES vault (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE item_uri (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_id INT NOT NULL, label VARCHAR(120) DEFAULT NULL, uri VARCHAR(2048) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_item_uri_item_id ON item_uri (item_id)');
        $this->addSql('ALTER TABLE item_uri ADD CONSTRAINT FK_F0A94D7A126F525E FOREIGN KEY (item_id) REFERENCES vault_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE custom_field (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_id INT NOT NULL, label VARCHAR(120) NOT NULL, type VARCHAR(40) NOT NULL, value TEXT DEFAULT NULL, is_sensitive BOOLEAN DEFAULT FALSE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_custom_field_item_id ON custom_field (item_id)');
        $this->addSql('ALTER TABLE custom_field ADD CONSTRAINT FK_2B1A7711126F525E FOREIGN KEY (item_id) REFERENCES vault_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_id INT NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL, size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_attachment_stored_name ON attachment (stored_name)');
        $this->addSql('CREATE INDEX idx_attachment_item_id ON attachment (item_id)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB126F525E FOREIGN KEY (item_id) REFERENCES vault_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE attachment');
        $this->addSql('DROP TABLE custom_field');
        $this->addSql('DROP TABLE item_uri');
        $this->addSql('DROP TABLE vault_item');
    }
}